#!/bin/bash

INCLUDE=()
STORE=()
while IFS= read -r line; do INCLUDE+=("$line"); done <$HOME/dotfiles/bookmarks.txt

for i in ${INCLUDE[@]}; do
    P="$HOME/$i"
    STORE+=$(find $P -maxdepth 1 -type d )
done
STORE+=("$HOME/dotfiles")

RESULT=$(printf "%s\n" "${STORE[@]}" | fzf)

[ -z $RESULT ] && exit

code $RESULT >/dev/null 2>&1
