#!/bin/bash

CMD="$1"
HOST="$2"
DEST="$3"

function add_host_redirection {
    exists=$(getent hosts $1)
    if [ -z "$exists" ]; then
        echo "127.0.0.1 $1" | sudo tee -a /etc/hosts >/dev/null
    fi
}

function wp_config_setup {
    path=$1
    username=$2
    password=$3
    [ ! -f $path/wp-config.php ] && cp $path/wp-config-sample.php $path/wp-config.php
    sed -i "s/username_here/$username/g;s/database_name_here/$username/g;s/password_here/$password/g;s/localhost/mariadb/g;" $path/wp-config.php
}

function root_domain {
    echo $1 | grep -oP '(.*?(?=\.\w{2,10}(\.\w{2,10})?$))'
}

function wp {
    host=$1
    # Download Wordpress
    if [ ! -f ~/www/wordpress.tar.gz ]; then
        curl https://en-gb.wordpress.org/latest-en_GB.tar.gz -o ~/www/wordpress.tar.gz
    fi
    # Extract Wordpress
    if [ ! -d ~/www/$host ]; then
        pushd ~/www >/dev/null
        tar xfz wordpress.tar.gz
        [ ! -z $host ] && mv ~/www/wordpress ~/www/$host
        popd >/dev/null
    fi
    # Add Hosts Redirection
    add_host_redirection $host
    # Setup Wordpress Config
    root=$(root_domain $host)
    wp_config_setup ~/www/$host "${root}_wp" secret
    # Setup Database
    pushd ~/www/dev >/dev/null
    docker compose exec mariadb mysql -uroot -psecret -e "CREATE USER IF NOT EXISTS ${root}_wp@'%' IDENTIFIED BY 'secret';"
    docker compose exec mariadb mysql -uroot -psecret -e "CREATE DATABASE IF NOT EXISTS ${root}_wp;"
    docker compose exec mariadb mysql -uroot -psecret -e "GRANT ALL PRIVILEGES ON ${root}_wp.* TO ${root}_wp@'%'"
    popd >/dev/null
    
}

function gen_extfile() {
    domain=$1
    cat <<EOF
		authorityKeyIdentifier=keyid,issuer\n
		basicConstraints=CA:FALSE\n
		keyUsage=digitalSignature,nonRepudiation,keyEncipherment,dataEncipherment\n
		subjectAltName = @alt_names\n
		[alt_names]\n
		DNS.1 = $domain
EOF
}

case "$CMD" in
wp)
    # execute devsetup script
    wp $HOST
    ;;
rebuild)
    pushd $HOME/www/dev
    docker compose build --parallel
    docker compose up -d --force-recreate
    ;;
restart)
    pushd $HOME/www/dev >/dev/null
    webconf-build
    docker compose restart nginx
    popd >/dev/null
    ;;
rootssl)
    [ -z "$2" ] && filename="rootCA" || filename="$2"
    openssl genrsa -des3 -passout pass:default -out "$filename.key" 4096
    openssl req -x509 -new -nodes -passin pass:default -key "$filename.key" -sha256 -days 20480 -subj "/C=GB/ST=London/L=London/O=Development/OU=IT Department/CN=Self Signed Certificate/emailAddress=info@example.com" -out rootCA.crt
    ;;
hostssl)
    if [ -z $HOST ]; then
        echo "Host argument is required"
        exit 1
    fi
    extFile=$(gen_extfile $HOST)
    openssl req -new -sha256 -nodes -out "$HOST.csr" -newkey rsa:2048 -days 20480 -subj "/C=GB/ST=London/L=London/O=$HOST/OU=IT Department/CN=$HOST Self Signed Certificate/emailAddress=info@$HOST" -keyout "$HOST.key"
    openssl x509 -req -passin pass:default -in "$HOST.csr" -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out "$HOST.crt" -days 500 -sha256 -extfile <(printf "$extFile")
    rm -f "$HOST.csr"
    # openssl pkcs12 -export -passin pass:default  -inkey "$HOST.key" -in "$HOST.crt" -out "$HOST.pfx" -passout pass:
    if ! [ -z $DEST ]; then
        mv "$HOST*" $DEST
    fi
    ;;
*) cat <<EOF ;;
ssl-cert: Generates

Allowed options:
    - restart                         restart web server
    - root {?filename} {?destination} generates root certificate. Default cirtificate basename is rootCA
    - host {host} {?destination}      generates domain certificate
EOF
esac
